version: '{build}'
os: Windows Server 2012
environment:
  JAVA_OPTS: -Dfile.encoding=UTF8
  SBT_OPTS: -Dfile.encoding=UTF8
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
  - cmd: choco install sbt -ia "INSTALLDIR=""C:\sbt"""
  - cmd: SET PATH=C:\sbt\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET SBT_OPTS=-Xmx4G -XX:MaxPermSize=1G
build_script:
  - sbt compile
test_script:
  # Keep the commands here in sync with .travis.yml
  - sbt +test
  - sbt +publishLocal
  - sbt 'project plugin' +test
  - sbt 'project plugin' +scripted
  - cd docs && sbt test validateDocs