[versions]
gradle-plugin-publish = "2.0.0"
nexus-publish = "2.0.0"
spotless = "8.1.0"
assertj = "3.27.6"
commons-io = "2.21.0"
commons-lang = "3.20.0"
freemarker = "2.3.34"

[libraries]
assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
commons-io = { group = "commons-io", name = "commons-io", version.ref = "commons-io" }
commons-lang = { group = "org.apache.commons", name = "commons-lang3", version.ref = "commons-lang" }
freemarker = { group = "org.freemarker", name = "freemarker", version.ref = "freemarker" }

[plugins]
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle-plugin-publish" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus-publish" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
